name: Build and Run Docker Container

on:
  push:
    branches:
      - main  # Triggers the action on push to the main branch

jobs:
  build:
    runs-on: self-hosted   # the runner we made  and configure with our server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          pwd
          whoami
          docker build -t vueimagejs .

      - name: Stop and Remove Existing Docker Container
        run: |
          if [ $(sudo docker ps -q -f name=vue_app) ]; then
            sudo docker stop vue_app
            sudo docker rm vue_app
          fi

      - name: Run Docker container
        run: docker container run -d --name vue_app -p 8081:80 vueimagejs
